---
version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Bogota
      - WEBUI_PORT=8080
    volumes:
      - /home/homeserver/.config/qbittorrent/config:/config
      - /mnt/hdd/downloads:/downloads
      - /mnt/hdd/torrents:/torrents
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    expose:
      - "6881"
      - "8080"
    networks:
      - mediaserver
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=claim-rnM64s9cZGeCkwuB8xws
    volumes:
      - /home/homeserver/.config/plex:/config
      - /mnt/hdd/series:/tv
      - /mnt/hdd/movies:/movies
      - /mnt/hdd/education:/education
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Bogota
    volumes:
      - /home/homeserver/.config/jackett:/config
      - /mnt/hdd/downloads/jackett:/downloads
    ports:
      - 9117:9117
    expose:
      - "9117"
    networks:
      - mediaserver
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Bogota
    volumes:
      - /home/homeserver/.config/sonarr:/config
      - /mnt/hdd/series:/tv
      - /mnt/hdd/downloads:/downloads
    ports:
      - 8989:8989
    expose:
      - "8989"
    networks:
      - mediaserver
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Bogota
    volumes:
      - /home/homeserver/.config/bazarr:/config
      - /mnt/hdd/movies:/movies
      - /mnt/hdd/series:/tv
    ports:
      - 6767:6767
    expose:
      - "6767"
    networks:
      - mediaserver
    restart: unless-stopped

networks:
  mediaserver:
