apiVersion: v1
kind: Pod
metadata:
  name: transmission
spec:
  restartPolicy: Always
  containers:
    - name: transmission
      image: linuxserver/transmission:4.0.6
      resources:
        requests:
          memory: "1Gi"
        limits:
          memory: "2Gi"
      env:
        - name: PUID
          value: "1001"
        - name: PGID
          value: "1001"
        - name: TZ
          value: "America/Bogota"
      ports:
        - containerPort: 51413
          hostPort: 51413
          protocol: TCP
        - containerPort: 51413
          hostPort: 51413
          protocol: UDP
        - containerPort: 9091
          hostPort: 9091
          protocol: TCP
      volumeMounts:
        - name: transmission-config
          mountPath: /config
        - name: downloads
          mountPath: /downloads
  volumes:
    - name: transmission-config
      hostPath:
        path: /home/homeserver/.config/transmission
        type: DirectoryOrCreate
    - name: downloads
      hostPath:
        path: /mnt/ssd/downloads
        type: DirectoryOrCreate
