---
- name: install systemd-resolved
  ansible.builtin.apt:
    name: systemd-resolved
    state: present

- name: configure systemd-resolved
  block:
    - name: uninstall openresolv
      ansible.builtin.apt:
        name: openresolv
        state: absent

    - name: create resolv.conf link
      ansible.builtin.file:
        src: /run/systemd/resolve/resolv.conf
        dest: /etc/resolv.conf
        state: link

    - name: set resolved.conf file
      ansible.builtin.copy:
        content: |
          [Resolve]
          DNS=1.1.1.1
          Cache=no
        dest: /etc/systemd/resolved.conf

- name: restart services
  block:
    - name: start DNS services
      ansible.builtin.service:
        name: systemd-resolved
        state: restarted
        enabled: true
