---
- name: Raspberry Pi base packages
  block:
    - name: install dependencies
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        - git
        - zsh
        - htop
        - vim
        - golang
        - python3
        - python3-pip
        - magic-wormhole
        - 7zip

    - name: set system swapiness
      ansible.posix.sysctl:
        name: vm.swappiness
        value: "0"
        state: present

    - name: Disable journal storage to disk
      community.general.ini_file:
        path: /etc/systemd/journald.conf
        section: Journal
        option: Storage
        value: volatile
        backup: true
