---
- name: Raspberry Pi base packages
  hosts: all
  become: yes
  tasks:
    - name: install dependencies
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        - git
        - zsh
        - vim

    - name: add docker GPG
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: add docker respository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: install docker
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io

    - name: make sure docker is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: install docker-compose
      pip:
        name: docker-compose
        state: present

    - name: set system swapiness
      ansible.posix.sysctl:
        name: vm.swappiness
        value: '0'
        state: present

  handlers:
    - name: restart docker
      service:
        name: docker
        state: restarted
