---
- name: docker compose
  hosts: all
  become: yes
  tasks:
    - name: docker compose templates
      template:
        src: templates/docker-services.j2
        dest: /etc/systemd/system/{{item}}-compose.service
      loop:
        - plex
        - qbittorrent

    - name: directories
      file:
        path: /opt/services/{{item}}
        state: directory
      loop:
        - plex
        - qbittorrent

    - name: compose stacks
      copy:
        src: files/{{item}}-compose.yaml
        dest: /opt/services/{{item}}/docker-compose.yaml
      loop:
        - plex
        - qbittorrent

    - name: enable services
      service:
        name: "{{item}}-compose.service"
        state: started
        enabled: yes
      loop:
        - plex
        - qbittorrent
