---
- name: Scripts setup
  hosts: all
  tasks:
    - name: setup scripts
      copy:
        src: "files/{{item}}"
        dest: "scripts/"
      loop:
        - organize-torrents.sh

    - name: scripts permissions
      file:
        path: "/home/pi/scripts/organize-torrents.sh"
        mode: "755"

    - name: organize torrents cron
      cron:
        name: organize-torrents
        minute: "*/1"
        job: "/home/pi/scripts/organize-torrents.sh"
        user: pi
