- name: Configure user for configs
  user:
    name: homeserver
    password: "homeserver"
    groups:
      - docker
    state: present
    shell: /bin/bash
    uid: 1001
    system: no
    createhome: yes

- name: Link homeserver config location to SSD drive
  block:
    - ansible.builtin.file:
        path: /mnt/ssd/raspifs/config
        state: directory

    - name: Set symlink for docker
      ansible.builtin.file:
        src: /mnt/ssd/raspifs/config
        dest: /home/homeserver/.config
        owner: homeserver
        group: homeserver
        state: link

- name: Configure pods to run
  block:
    - name: ensure config directory exists
      file:
        path: /etc/kubelet.conf.d
        state: directory

    - name: Copy container configs
      ansible.posix.synchronize:
        src: configs/
        dest: /etc/kubelet.conf.d
        delete: true

    - name: Change config files ownership to be read by any user
      file:
        dest: /etc/kubelet.conf.d
        owner: root
        group: root
        mode: "u=rwX,g=rX,o=rX"
        recurse: true

    - name: Synchronization of src on the control machine to dest on the remote hosts
      ansible.posix.synchronize:
        src: specs/
        dest: /etc/kubelet.d
        delete: true

- name: ensure services are running
  block:
    - name: Start container services
      loop:
        - docker
        - cri-docker.service
        - kubelet
      systemd:
        name: "{{ item }}"
        state: started

    - name: wait for kubelet to start
      wait_for: port=10250 timeout=60
