- name: Configure user for configs
  user:
    name: homeserver
    password: "homeserver"
    groups:
      - docker
    state: present
    shell: /bin/bash
    system: no
    createhome: yes

- name: Configure pods to run
  block:
    - name: cleanup pods
      shell: |
        rm -rf /etc/kubelet.d/*

    - name: Copy pods specs
      copy:
        src: "{{item}}"
        dest: /etc/kubelet.d
      with_fileglob:
        - "*.yaml"

    - name: restart kubelet
      service:
        name: kubelet
        state: restarted
