- name: Configure user for configs
  user:
    name: homeserver
    password: "homeserver"
    groups:
      - docker
    state: present
    shell: /bin/bash
    system: no
    createhome: yes

- name: Configure pods to run
  block:
    - name: Synchronization of src on the control machine to dest on the remote hosts
      ansible.posix.synchronize:
        src: ./
        dest: /etc/kubelet.d
