apiVersion: v1
kind: Pod
metadata:
  name: pihole
spec:
  hostNetwork: true
  restartPolicy: Always
  containers:
    - name: pihole
      image: pihole/pihole:latest
      env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/Chicago"
        - name: PIHOLE_DNS_
          value: "1.1.1.1;1.0.0.1;9.9.9.9;149.112.112.112"
        - name: DNSMASQ_LISTENING
          value: "all"
      ports:
        - containerPort: 53
          hostPort: 53
          protocol: TCP
        - containerPort: 53
          hostPort: 53
          protocol: UDP
        - containerPort: 80
          hostPort: 80
          protocol: TCP
      volumeMounts:
        - name: etc-pihole
          mountPath: /etc/pihole
        - name: etc-dnsmasq
          mountPath: /etc/dnsmasq.d
        - name: resolv-conf
          mountPath: /etc/resolv.conf
          readOnly: true
  volumes:
    - name: etc-pihole
      hostPath:
        path: /home/homeserver/.config/etc-pihole
        type: "DirectoryOrCreate"
    - name: etc-dnsmasq
      hostPath:
        path: /home/homeserver/.config/etc-dnsmasq.d
        type: "DirectoryOrCreate"
    - name: resolv-conf
      hostPath:
        path: /etc/resolv.conf
        type: "File"
