apiVersion: v1
kind: Pod
metadata:
  name: changedetection.io
spec:
  hostNetwork: true
  restartPolicy: Always
  containers:
    - name: changedetection
      image: dgtlmoon/changedetection.io:0.45.24
      ports:
        - containerPort: 5000
          hostPort: 5000
          protocol: TCP
      volumeMounts:
        - name: datastore
          mountPath: /datastore
  volumes:
    - name: datastore
      hostPath:
        path: /home/homeserver/.config/changedetection
        type: "DirectoryOrCreate"
