apiVersion: v1
kind: Pod
metadata:
  name: changedetection.io
spec:
  restartPolicy: Always
  containers:
    - name: changedetection
      image: dgtlmoon/changedetection.io:0.45.25
      env:
        - name: PLAYWRIGHT_DRIVER_URL
          value: ws://localhost:3000
      ports:
        - containerPort: 5000
          hostPort: 5000
          protocol: TCP
      volumeMounts:
        - name: datastore
          mountPath: /datastore
    - name: browserless
      image: dgtlmoon/sockpuppetbrowser:latest
      env:
        - name: CONCURRENT
          value: "10"
      ports:
        - containerPort: 3000
          protocol: TCP
      volumeMounts:
        - name: shm
          mountPath: /dev/shm
  volumes:
    - name: datastore
      hostPath:
        path: /home/homeserver/.config/changedetection
        type: "DirectoryOrCreate"
    - name: shm
      emptyDir:
        medium: Memory
