apiVersion: v1
kind: Pod
metadata:
  name: heimdall
spec:
  restartPolicy: Always
  containers:
    - name: heimdall
      image: lscr.io/linuxserver/heimdall:v2.6.3-ls293
      env:
        - name: PUID
          value: "1001"
        - name: PGID
          value: "1001"
        - name: TZ
          value: "America/Bogota"
      ports:
        - containerPort: 80
          hostPort: 81
        # - containerPort: 443
        #   hostPort: 443
      volumeMounts:
        - name: config
          mountPath: /config
  volumes:
    - name: config
      hostPath:
        path: /home/homeserver/.config/heimdall
        type: "DirectoryOrCreate"
