apiVersion: v1
kind: Pod
metadata:
  name: media
spec:
  restartPolicy: Always
  containers:
    - name: sonarr
      image: linuxserver/sonarr:4.0.5
      env: &environment
        - name: PUID
          value: "1001"
        - name: PGID
          value: "1001"
        - name: TZ
          value: "America/Bogota"
      ports:
        - containerPort: 8989
          hostPort: 8989
          protocol: TCP
      volumeMounts:
        - name: sonarr-config
          mountPath: /config
        - name: tv-data
          mountPath: /data/tv
    - name: radarr
      image: linuxserver/radarr:5.7.0
      env: *environment
      ports:
        - containerPort: 7878
          hostPort: 7878
          protocol: TCP
      volumeMounts:
        - name: radarr-config
          mountPath: /config
        - name: movie-data
          mountPath: /data/movies
    - name: readarr
      image: lscr.io/linuxserver/readarr:0.3.28-develop
      env: *environment
      ports:
        - containerPort: 8787
          hostPort: 8787
          protocol: TCP
      volumeMounts:
        - name: readarr-config
          mountPath: /config
        - name: book-data
          mountPath: /books

    - name: bazarr
      image: linuxserver/bazarr:1.4.3
      env: *environment
      ports:
        - containerPort: 6767
          hostPort: 6767
          protocol: TCP
      volumeMounts:
        - name: bazarr-config
          mountPath: /config
        - name: tv-data
          mountPath: /data/tv
        - name: movie-data
          mountPath: /data/movies

    - name: jellyseer
      image: fallenbagel/jellyseerr:1.9.2
      env:
        - name: TZ
          value: "America/Bogota"
        - name: PORT
          value: "5056"
      ports:
        - containerPort: 5056
          hostPort: 5056
      volumeMounts:
        - name: jellyseer-config
          mountPath: /app/config

    - name: prowlarr
      image: lscr.io/linuxserver/prowlarr:1.19.0
      env: *environment
      ports:
        - containerPort: 9696
          hostPort: 9696
      volumeMounts:
        - name: prowlarr-config
          mountPath: /config

    - name: flaresolverr
      securityContext:
        allowPrivilegeEscalation: false
      image: flaresolverr/flaresolverr:v3.3.21
      env:
        - name: TZ
          value: "America/Bogota"
        - name: LOG_LEVEL
          value: "info"
        - name: LOG_HTML
          value: "false"
        - name: CAPTCHA_SOLVER
          value: "none"
      ports:
        - containerPort: 8191
          hostPort: 8191

    - name: tautulli
      image: lscr.io/linuxserver/tautulli:2.14.3
      env: *environment
      ports:
        - containerPort: 8181
          hostPort: 8181
      volumeMounts:
        - name: tautulli-config
          mountPath: /config

    - name: qbittorrent
      image: lscr.io/linuxserver/qbittorrent:4.6.5
      resources:
        requests:
          memory: "1Gi"
        limits:
          memory: "2Gi"
      env: *environment
      ports:
        - containerPort: 6881
          hostPort: 6881
          protocol: TCP
        - containerPort: 6881
          hostPort: 6881
          protocol: UDP
        - containerPort: 8080
          hostPort: 8080
          protocol: TCP
      volumeMounts:
        - name: qbittorrent-config
          mountPath: /config
        - name: qbittorrent-incomplete-data
          mountPath: /data/incomplete
        - name: movie-data
          mountPath: /data/movies
        - name: tv-data
          mountPath: /data/tv
        - name: book-data
          mountPath: /data/book

  volumes:
    - name: sonarr-config
      hostPath:
        path: /home/homeserver/.config/sonarr
        type: "DirectoryOrCreate"
    - name: bazarr-config
      hostPath:
        path: /home/homeserver/.config/bazarr
        type: "DirectoryOrCreate"
    - name: radarr-config
      hostPath:
        path: /home/homeserver/.config/radarr
        type: "DirectoryOrCreate"
    - name: readarr-config
      hostPath:
        path: /home/homeserver/.config/readarr
        type: "DirectoryOrCreate"
    - name: prowlarr-config
      hostPath:
        path: /home/homeserver/.config/prowlarr
        type: "DirectoryOrCreate"
    - name: jellyseer-config
      hostPath:
        path: /home/homeserver/.config/jellyseer
        type: "DirectoryOrCreate"
    - name: tautulli-config
      hostPath:
        path: /home/homeserver/.config/jellyseer
        type: "DirectoryOrCreate"
    - name: qbittorrent-config
      hostPath:
        path: /home/homeserver/.config/qbittorrent
        type: "DirectoryOrCreate"

    - name: tv-data
      hostPath:
        path: /mnt/hdd/mediaserver/tv
        type: "Directory"
    - name: movie-data
      hostPath:
        path: /mnt/hdd/mediaserver/movies
        type: "Directory"
    - name: book-data
      hostPath:
        path: /mnt/hdd/mediaserver/books
        type: "DirectoryOrCreate"
    - name: qbittorrent-incomplete-data
      hostPath:
        path: /mnt/ssd/qbittorrent/incomplete
        type: "DirectoryOrCreate"
