apiVersion: v1
kind: Pod
metadata:
  name: media
spec:
  hostNetwork: true
  restartPolicy: Always
  containers:
    - name: jackett
      image: linuxserver/jackett:0.22.175
      env: &environment
        - name: PUID
          value: "1001"
        - name: PGID
          value: "1001"
        - name: TZ
          value: "America/Bogota"
      ports:
        - containerPort: 9117
          hostPort: 9117
          protocol: TCP
      volumeMounts:
        - name: jackett-config
          mountPath: /config
        - name: jackett-download
          mountPath: /downloads
    - name: bazarr
      image: linuxserver/bazarr:1.4.3
      env: *environment
      ports:
        - containerPort: 6767
          hostPort: 6767
          protocol: TCP
      volumeMounts:
        - name: bazarr-config
          mountPath: /config
        - name: tv-data
          mountPath: /data/tv
        - name: movie-data
          mountPath: /data/movies

    - name: sonarr
      image: linuxserver/sonarr:4.0.5
      env: *environment
      ports:
        - containerPort: 8989
          hostPort: 8989
          protocol: TCP
      volumeMounts:
        - name: sonarr-config
          mountPath: /config
        - name: tv-data
          mountPath: /data/tv
    - name: radarr
      image: linuxserver/radarr:5.7.0
      env: *environment
      ports:
        - containerPort: 7878
          hostPort: 7878
          protocol: TCP
      volumeMounts:
        - name: radarr-config
          mountPath: /config
        - name: movie-data
          mountPath: /data/movies

    # - name: overseer
    #   image: sctx/overseerr:latest
    #   env:
    #     - name: TZ
    #       value: "America/Bogota"
    #     - name: PORT
    #       value: "5055"
    #   ports:
    #     - containerPort: 5055
    #       hostPort: 5055
    #   volumeMounts:
    #     - name: overseer-config
    #       mountPath: /app/config

    - name: jellyseer
      image: fallenbagel/jellyseerr:1.9.2
      env:
        - name: TZ
          value: "America/Bogota"
        - name: PORT
          value: "5056"
      ports:
        - containerPort: 5056
          hostPort: 5056
      volumeMounts:
        - name: jellyseer-config
          mountPath: /app/config

    - name: tautulli
      image: lscr.io/linuxserver/tautulli:latest
      env: *environment
      ports:
        - containerPort: 8181
          hostPort: 8181
      volumeMounts:
        - name: tautulli-config
          mountPath: /config

  volumes:
    - name: jackett-config
      hostPath:
        path: /home/homeserver/.config/jackett
        type: "DirectoryOrCreate"
    - name: sonarr-config
      hostPath:
        path: /home/homeserver/.config/sonarr
        type: "DirectoryOrCreate"
    - name: bazarr-config
      hostPath:
        path: /home/homeserver/.config/bazarr
        type: "DirectoryOrCreate"
    - name: radarr-config
      hostPath:
        path: /home/homeserver/.config/radarr
        type: "DirectoryOrCreate"
    # - name: overseer-config
    #   hostPath:
    #     path: /home/homeserver/.config/overseer
    #     type: "DirectoryOrCreate"
    - name: jellyseer-config
      hostPath:
        path: /home/homeserver/.config/jellyseer
        type: "DirectoryOrCreate"
    - name: tautulli-config
      hostPath:
        path: /home/homeserver/.config/jellyseer
        type: "DirectoryOrCreate"
    - name: jackett-download
      hostPath:
        path: /mnt/hdd/mediaserver/jackett
        type: "DirectoryOrCreate"
    - name: tv-data
      hostPath:
        path: /mnt/hdd/mediaserver/tv
        type: "Directory"
    - name: movie-data
      hostPath:
        path: /mnt/hdd/mediaserver/movies
        type: "Directory"
