apiVersion: v1
kind: Pod
metadata:
  name: nginx-proxy
spec:
  restartPolicy: Always
  containers:
    - name: nginx
      image: nginx:1.27.0-alpine
      ports:
        - containerPort: 80
          hostPort: 80
          protocol: TCP
      volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          readOnly: true
        - name: nginx-default-config
          mountPath: /etc/nginx/conf.d/default.conf
          readOnly: true
  volumes:
    - name: nginx-config
      hostPath:
        path: /etc/kubelet.conf.d/nginx/nginx.conf
        type: "File"
    - name: nginx-default-config
      hostPath:
        path: /etc/kubelet.conf.d/nginx/default.conf
        type: "File"
