apiVersion: v1
kind: Pod
metadata:
  name: openhab
spec:
  hostNetwork: true
  restartPolicy: Always
  containers:
    - name: openhab
      image: openhab/openhab:4.1.3
      env:
        - name: USER_ID
          value: "1001"
        - name: GROUP_ID
          value: "1001"
        - name: CRYPTO_POLICY
          value: "unlimited"
        - name: OPENHAB_HTTP_PORT
          value: "8090"
        - name: OPENHAB_HTTPS_PORT
          value: "8091"

      volumeMounts:
        - name: conf
          mountPath: /openhab/conf
        - name: addons
          mountPath: /openhab/addons
        - name: userdata
          mountPath: /openhab/userdata

        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
        - name: timezone
          mountPath: /etc/timezone
          readOnly: true
  volumes:
    - name: conf
      hostPath:
        path: /home/homeserver/.config/openhab/conf
        type: "DirectoryOrCreate"
    - name: addons
      hostPath:
        path: /home/homeserver/.config/openhab/addons
        type: "DirectoryOrCreate"
    - name: userdata
      hostPath:
        path: /home/homeserver/.config/openhab/userdata
        type: "DirectoryOrCreate"

    - name: localtime
      hostPath:
        path: /etc/localtime
        type: "File"
    - name: timezone
      hostPath:
        path: /etc/timezone
        type: "File"
