apiVersion: v1
kind: Pod
metadata:
  name: qbittorrent
spec:
  restartPolicy: Always
  containers:
    - name: qbittorrent
      image: lscr.io/linuxserver/qbittorrent:4.6.5
      resources:
        requests:
          memory: "1Gi"
        limits:
          memory: "2Gi"
      env:
        - name: PUID
          value: "1001"
        - name: PGID
          value: "1001"
        - name: TZ
          value: "America/Bogota"
        - name: WEBUI_PORT
          value: "8080"
      ports:
        - containerPort: 6881
          hostPort: 6881
          protocol: TCP
        - containerPort: 6881
          hostPort: 6881
          protocol: UDP
        - containerPort: 8080
          hostPort: 8080
          protocol: TCP
      volumeMounts:
        - name: config
          mountPath: /config
        - name: incomplete-data
          mountPath: /data/incomplete
        - name: movie-data
          mountPath: /data/movies
        - name: tv-data
          mountPath: /data/tv
  volumes:
    - name: config
      hostPath:
        path: /home/homeserver/.config/qbittorrent
        type: "DirectoryOrCreate"
    - name: incomplete-data
      hostPath:
        path: /mnt/ssd/qbittorrent/incomplete
        type: "DirectoryOrCreate"
    - name: tv-data
      hostPath:
        path: /mnt/hdd/mediaserver/tv
        type: "Directory"
    - name: movie-data
      hostPath:
        path: /mnt/hdd/mediaserver/movies
        type: "Directory"
