version: "3"

services:
  changedetection:
    container_name: changedetection.io
    image: dgtlmoon/changedetection.io
    ports:
      - "5000:5000"
    volumes:
      - '/home/homeserver/.config/changedetection:/datastore'
    restart: always
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
