version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      # - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "700:80/tcp"
    environment:
      PUID: 1000
      PGID: 1000
      TZ: 'America/Chicago'
      PIHOLE_DNS_: '1.1.1.1;1.0.0.1;9.9.9.9;149.112.112.112'
      DNSMASQ_LISTENING: 'all'
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      - '/home/homeserver/.config/etc-pihole:/etc/pihole'
      - '/home/homeserver/.config/etc-dnsmasq.d:/etc/dnsmasq.d'
      - '/etc/resolv.conf:/etc/resolv.conf:ro'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    # cap_add:
      # - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
