# Reference: https://tailscale.com/kb/1103/exit-nodes?tab=linux

- name: Set mounts and symlinks
  block:
    - ansible.builtin.file:
        path: /mnt/ssd/tailscale
        state: directory

    - name: Set symlink for docker
      ansible.builtin.file:
        src: /mnt/ssd/tailscale
        dest: /var/lib/tailscale
        state: link

- name: Install tailscale
  block:
    - name: Install from official script
      ansible.builtin.shell: |
        curl -fsSL https://tailscale.com/install.sh | sh

    - name: Ensure tailscale service is not running
      ansible.builtin.service:
        name: tailscaled
        state: stopped

- name: change tailscale service file
  block:
    - name: copy environment file
      ansible.builtin.copy:
        src: tailscaled
        dest: /etc/default/
        owner: root
        group: root
        mode: "0444"

    - name: copy tailscale service file
      ansible.builtin.copy:
        src: tailscaled.service
        dest: /lib/systemd/system/
        owner: root
        group: root
        mode: "0444"

    - name: setup tailscale service
      ansible.builtin.service:
        name: tailscaled.service
        state: restarted
        daemon_reload: true
        enabled: true

- name: Configure systemwide options
  block:
    - name: create sysctl tailscale config file
      ansible.builtin.file:
        path: /etc/sysctl.d/99-tailscale.conf
        state: touch

    - name: enable ip forwarding
      ansible.builtin.lineinfile:
        path: /etc/sysctl.d/99-tailscale.conf
        line: "{{ item }}"
      with_items:
        - "net.ipv4.ip_forward                 = 1"
        - "net.ipv6.conf.all.forwarding        = 1"

    - name: apply sysctl params without reboot
      ansible.builtin.command: sysctl --system

    - name: set it as an exit node
      ansible.builtin.shell: |
        tailscale set --advertise-exit-node
